// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	// LIMIT $1：這表示最多返回 $1 行記錄，這裡的 $1 是一個佔位符，實際值在查詢執行時由使用者傳入。這讓查詢能夠靈活控制要返回的記錄數。
	// OFFSET $2：這表示從第 $2 行開始返回結果，這裡的 $2 也是一個佔位符。這通常用於實現分頁功能，可以跳過前面指定的行數。
	// LIMIT $1** 和 OFFSET $2： 這兩個佔位符可以用來實現查詢的分頁功能。舉例來說，LIMIT 10 和 OFFSET 20 將返回第 21 到第 30 條記錄，這使得查詢結果可以按頁分割和顯示。
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
